# Usar imagen base de Apache
FROM httpd:latest

# Habilitar mod_rewrite y SSL
RUN a2enmod rewrite ssl

# Copiar los certificados SSL
COPY mywall-eks.work.gd.crt /etc/ssl/certs/
COPY mywall-eks.work.gd.key /etc/ssl/private/
COPY mywall-eks.work.gd.ca-bundle /etc/ssl/certs/

# Copiar la configuración de Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Exponer puertos HTTP y HTTPS
EXPOSE 80 443