apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany           # Permite múltiples lecturas/escrituras
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi           # Solicita 5GB de almacenamiento