apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1                    # Número de pods
  selector:
    matchLabels:
      app: php-apache           # Selector para identificar pods
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: ferminromero00/mywall:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs-storage
          mountPath: /var/www/html  # Monta EFS en esta ruta
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc        # Usa el PVC definido