apiVersion: v1
kind: Service
metadata:
  name: php-apache-clusterip    # Nombre del servicio
spec:
  type: ClusterIP              # Tipo de servicio para comunicación interna
  ports:
    - name: http
      port: 80                 # Puerto del servicio
      targetPort: 80          # Puerto del pod
      protocol: TCP
    - name: https
      port: 443               # Puerto HTTPS del servicio
      targetPort: 443         # Puerto HTTPS del pod
      protocol: TCP
  selector:
    app: php-apache           # Selecciona pods con esta etiqueta